# The ubuntu and windows workflows were in single file, separating for independent build status batches
name: CMake Windows

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: cmake ..
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
#     - name: test
#       run: cd build && ctest
